apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
name: aks-simple-001
labels:
example: simple-aks
environment: development
spec:
forProvider:
location: West Europe
resourceGroupNameSelector:
matchLabels:
example: simple-aks

```
dnsPrefix: aks-simple-001
kubernetesVersion: "1.28.3"

# Default node pool
defaultNodePool:
  - name: system
    nodeCount: 3
    vmSize: Standard_D2s_v3
    enableAutoScaling: true
    minCount: 1
    maxCount: 5
    osDiskSizeGb: 30
    vnetSubnetIdSelector:
      matchLabels:
        example: simple-aks
        purpose: aks

# System-assigned managed identity
identity:
  - type: SystemAssigned

# Network profile
networkProfile:
  - networkPlugin: azure
    networkPolicy: calico
    dnsServiceIp: 10.2.0.10
    serviceCidr: 10.2.0.0/24
    loadBalancerSku: standard

# Disable unnecessary add-ons for simplicity
addonProfile:
  - httpApplicationRouting:
      - enabled: false
    omsAgent:
      - enabled: false
    azurePolicy:
      - enabled: false
```

providerConfigRef:
name: default

# Write kubeconfig to secret

writeConnectionSecretToRef:
name: aks-simple-001-kubeconfig
namespace: default
