apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
name: rg-simple-aks
labels:
example: simple-aks
environment: development
managed-by: crossplane
spec:
forProvider:
location: West Europe
providerConfigRef:
name: default
