apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/management/crossplane-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: crossplane
      namespace: crossplane-system
    - apiVersion: apps/v1
      kind: Deployment
      name: crossplane-rbac-manager
      namespace: crossplane-system
  timeout: 5m
  wait: true
