apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/component: infrastructure
    managed-by: flux
    toolkit.fluxcd.io/namespace: flux-system
