apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaksclusters.platform.example.org
spec:
  group: platform.example.org
  names:
    kind: XAKSCluster
    plural: xaksclusters
  claimNames:
    kind: AKSCluster
    plural: aksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    # Cluster identification
                    clusterName:
                      type: string
                      description: Name of the AKS cluster
                    
                    # Size configuration
                    size:
                      type: string
                      description: Cluster size (small, medium, large)
                      enum:
                        - small
                        - medium
                        - large
                      default: small
                    
                    # Location
                    location:
                      type: string
                      description: Azure region
                      default: West Europe
                      enum:
                        - West Europe
                        - North Europe
                        - East US
                        - West US
                    
                    # Kubernetes version
                    kubernetesVersion:
                      type: string
                      description: Kubernetes version
                      default: "1.28"
                    
                    # Networking
                    networkPlugin:
                      type: string
                      description: Network plugin (azure or kubenet)
                      enum:
                        - azure
                        - kubenet
                      default: azure
                    
                    # Environment
                    environment:
                      type: string
                      description: Environment (dev, staging, production)
                      enum:
                        - dev
                        - staging
                        - production
                      default: dev
                  
                  required:
                    - clusterName
              
              required:
                - parameters
            
            status:
              type: object
              properties:
                clusterStatus:
                  description: Status of the AKS cluster
                  type: string
                endpoint:
                  description: Cluster API endpoint
                  type: string
                resourceGroupName:
                  description: Name of the created resource group
                  type: string
